//Users
export const GET_ALL_USERS_REQUESTED = 'GET_ALL_USERS_REQUESTED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

//Posts
export const GET_ALL_POSTS_REQUESTED = 'GET_ALL_POSTS_REQUESTED';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

//Comments
export const GET_ALL_COMMENTS_REQUESTED = 'GET_ALL_COMMENTS_REQUESTED';
export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILED = 'GET_ALL_COMMENTS_FAILED';

//Filtered Posts by id
export const GET_POSTS_BY_USERSID_REQUESTED = 'GET_POSTS_BY_USERSID_REQUESTED';
export const GET_POSTS_BY_USERSID_SUCCESS = 'GET_POSTS_BY_USERSID_SUCCESS';
export const GET_POSTS_BY_USERSID_FAILED = 'GET_POSTS_BY_USERSID_FAILED';
