//Users
export const GET_ALL_USERS_REQUESTED = 'GET_ALL_USERS_REQUESTED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

//Posts
export const GET_ALL_POSTS_REQUESTED = 'GET_ALL_POSTS_REQUESTED';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

//Comments by post id
export const GET_ALL_COMMENTS_BY_POSTID_REQUESTED = 'GET_ALL_COMMENTS_BY_POSTID_REQUESTED';
export const GET_ALL_COMMENTS_BY_POSTID_SUCCESS = 'GET_ALL_COMMENTS_BY_POSTID_SUCCESS';
export const GET_ALL_COMMENTS_BY_POSTID_FAILED = 'GET_ALL_COMMENTS_BY_POSTID_FAILED';

//Filtered Posts by id
export const GET_POSTS_BY_USERSID_REQUESTED = 'GET_POSTS_BY_USERSID_REQUESTED';
export const GET_POSTS_BY_USERSID_SUCCESS = 'GET_POSTS_BY_USERSID_SUCCESS';
export const GET_POSTS_BY_USERSID_FAILED = 'GET_POSTS_BY_USERSID_FAILED';

//Posts by post id
export const GET_ALL_POSTS_BY_POSTID_REQUESTED = 'GET_ALL_POSTS_BY_POSTID_REQUESTED';
export const GET_ALL_POSTS_BY_POSTID_SUCCESS = 'GET_ALL_POSTS_BY_POSTID_SUCCESS';
export const GET_ALL_POSTS_BY_POSTID_FAILED = 'GET_ALL_POSTS_BY_POSTID_FAILED';