//Users
export const GET_ALL_USERS_REQUESTED = 'GET_ALL_USERS_REQUESTED';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';

//Posts
export const GET_ALL_POSTS_REQUESTED = 'GET_ALL_POSTS_REQUESTED';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAILED = 'GET_ALL_POSTS_FAILED';

//Comments by post id
export const GET_ALL_COMMENTS_BY_POST_ID_REQUESTED = 'GET_ALL_COMMENTS_BY_POST_ID_REQUESTED';
export const GET_ALL_COMMENTS_BY_POST_ID_SUCCESS = 'GET_ALL_COMMENTS_BY_POST_ID_SUCCESS';
export const GET_ALL_COMMENTS_BY_POST_ID_FAILED = 'GET_ALL_COMMENTS_BY_POST_ID_FAILED';

//Filtered Posts by users id
export const GET_POSTS_BY_USERS_ID_REQUESTED = 'GET_POSTS_BY_USERS_ID_REQUESTED';
export const GET_POSTS_BY_USERS_ID_SUCCESS = 'GET_POSTS_BY_USERS_ID_SUCCESS';
export const GET_POSTS_BY_USERS_ID_FAILED = 'GET_POSTS_BY_USERS_ID_FAILED';

//Post by post id
export const GET_ALL_POST_BY_ID_REQUESTED = 'GET_ALL_POST_BY_ID_REQUESTED';
export const GET_ALL_POST_BY_ID_SUCCESS = 'GET_ALL_POST_BY_ID_SUCCESS';
export const GET_ALL_POST_BY_ID_FAILED = 'GET_ALL_POST_BY_ID_FAILED';
